name: "[Release] Create Release"

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ github.token }}

  publish-to-hex:
    name: Publish to Hex
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          # Mostly to avoid GitHub rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Install Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build docs
        run: nix develop --impure -c rebar3 hex build

      - name: Publish to Hex
        run: nix develop --impure -c rebar3 hex publish --repo hexpm --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
          DEBUG: 1
